<?php

/**
 * Implements hook_views_query_alter().
 */
function gc_custom_views_query_alter(&$view, &$query) {

  // (Example assuming a view with an exposed filter on node title.)
  // If the input for the title filter is a positive integer, filter against
  // node ID instead of node title.
  if ($view->name == 'concerts') {
    $selected_date = $view->args[1];
    if($selected_date){
      $view->query->add_where_expression(
        1,
        "DATE_FORMAT(field_data_field_date.field_date_value, '%Y-%m-%d') = :field_data_field_date_field_date_value_2", 
        array(':field_data_field_date_field_date_value_2' => $selected_date)
      );
    }
  }
}