<?php

include_once 'includes/buy_link.inc';

/**
 * Implements hook_views_query_alter().
 * fix to read the date argument which was otherwise not parsed
 */
function gc_custom_views_query_alter(&$view, &$query) {

  // (Example assuming a view with an exposed filter on node title.)
  // If the input for the title filter is a positive integer, filter against
  // node ID instead of node title.
  if ($view->name == 'concerts' && $view->current_display == 'home_list') {
    $selected_date = $view->args[1];
    if($selected_date){
      $view->query->add_where_expression(
        1,
        "DATE_FORMAT(field_data_field_date.field_date_value, '%Y-%m-%d') = :field_data_field_date_field_date_value_2", 
        array(':field_data_field_date_field_date_value_2' => $selected_date)
      );
    }
  }
}


/*
 * provide link formatter to show buy/acheter links
 */
function gc_custom_field_formatter_info() {
  $info = [];
  $info['buy_link'] = _buy_link_formatter_info();
  dpm(_buy_link_formatter_info());
  return $info;
}

function gc_custom_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch($display['type']){
    case 'buy_link':
      return _buy_link_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display);
      break;
  }
}
